DROP TABLE IF EXISTS TIN_NHAN, DANH_GIA, YEU_THICH, CHI_TIET_DON_HANG, DON_HANG, SAN_PHAM, KHUYEN_MAI, LOAI_SAN_PHAM, QUAN_TRI_VIEN, CUA_HANG, KHACH_HANG CASCADE;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE KHACH_HANG (
    KH_MA SERIAL PRIMARY KEY,
    KH_TEN VARCHAR(150) NOT NULL,
    KH_EMAIL VARCHAR(150) UNIQUE,
    KH_SDT VARCHAR(20),
    KH_DIACHI TEXT,
    KH_MATKHAU VARCHAR(255),
    KH_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KH_KHOA BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE CUA_HANG (
    CH_MA SERIAL PRIMARY KEY,
    CH_TEN VARCHAR(255) NOT NULL,
    CH_DIACHI TEXT NOT NULL,
    CH_XAPHUONG VARCHAR(255),
    CH_THANHPHO VARCHAR(255),
    CH_SDT VARCHAR(20),
    MATINH VARCHAR(20),
    MAXA VARCHAR(20),
    SONHA_DUONG VARCHAR(255),
    GIO_MO_CUA VARCHAR(20),
    GIO_DONG_CUA VARCHAR(20),
    CH_TRANGTHAI BOOLEAN DEFAULT false,
    CH_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LOAI_SAN_PHAM (
    L_MA SERIAL PRIMARY KEY,
    L_TEN VARCHAR(255) NOT NULL,
    L_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE KHUYEN_MAI (
    KM_MA SERIAL PRIMARY KEY,
    KM_TEN VARCHAR(255) NOT NULL,
    KM_MOTA TEXT,
    KM_PHANTRAM INT NOT NULL CHECK (KM_PHANTRAM BETWEEN 1 AND 100),
    KM_NGAYBATDAU DATE NOT NULL,
    KM_NGAYKETTHUC DATE NOT NULL,
    KM_TRANGTHAI BOOLEAN DEFAULT true,
    KM_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SAN_PHAM (
    SP_MA SERIAL PRIMARY KEY,
    SP_TEN VARCHAR(255) NOT NULL,
    SP_GIA NUMERIC(12,2) NOT NULL,
    SP_MOTA TEXT,
    SP_HINH VARCHAR(255),
    L_MA INT REFERENCES LOAI_SAN_PHAM(L_MA) ON DELETE SET NULL,
    KM_MA INT REFERENCES KHUYEN_MAI(KM_MA) ON DELETE SET NULL,
    SP_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SP_NGAYCAPNHAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SP_TONKHO INT NOT NULL DEFAULT 0
);

INSERT INTO LOAI_SAN_PHAM (L_TEN) VALUES
('Bánh ngọt'),
('Trà sữa'),
('Café'),
('Trà trái cây');

CREATE TABLE DON_HANG (
    DH_MA SERIAL PRIMARY KEY,
    KH_MA INT REFERENCES KHACH_HANG(KH_MA) ON DELETE SET NULL,
    DH_TENKH VARCHAR(255),
    DH_SDT VARCHAR(20),
    DH_DIACHI TEXT,
    DH_HTNHAN VARCHAR(50),
    CH_MA INT REFERENCES CUA_HANG(CH_MA) ON DELETE SET NULL,
    DH_TONGTIEN NUMERIC(12,2),
    DH_TRANGTHAI VARCHAR(50) DEFAULT 'pending',
    DH_PTTT VARCHAR(20) DEFAULT 'cod', -- cod | momo | vnpay | bank_transfer
    DH_TT_TRANGTHAI VARCHAR(20) DEFAULT 'unpaid', -- unpaid | pending | paid | failed | refunded
    DH_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CHI_TIET_DON_HANG (
    CTDH_MA SERIAL PRIMARY KEY,
    DH_MA INT REFERENCES DON_HANG(DH_MA) ON DELETE CASCADE,
    SP_MA INT REFERENCES SAN_PHAM(SP_MA) ON DELETE CASCADE,
    CTDH_SOLUONG INT NOT NULL,
    CTDH_GIA NUMERIC(12,2) NOT NULL,
    CTDH_THANHTIEN NUMERIC(12,2) NOT NULL
);

-- Giao dịch thanh toán trực tuyến (MoMo/VNPAY...) — tách khỏi DON_HANG vì một đơn
-- có thể có nhiều lần thử thanh toán, còn DH_TT_TRANGTHAI chỉ phản ánh kết quả sau cùng.
CREATE TABLE GIAO_DICH_THANH_TOAN (
    GD_MA SERIAL PRIMARY KEY,
    DH_MA INT NOT NULL REFERENCES DON_HANG(DH_MA) ON DELETE CASCADE,
    GD_NHACC VARCHAR(30) NOT NULL, -- momo | vnpay
    GD_PTTT VARCHAR(30), -- wallet | qr | atm | intcard ...
    GD_SOTIEN NUMERIC(15,0) NOT NULL,
    GD_MA_YEUCAU VARCHAR(100),
    GD_MA_GIAODICH VARCHAR(100),
    GD_TRANGTHAI VARCHAR(20) NOT NULL DEFAULT 'pending', -- pending | success | failed
    GD_MA_PHANHOI VARCHAR(50),
    GD_PHANHOI_THO TEXT,
    GD_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    GD_NGAYTT TIMESTAMP
);

CREATE INDEX idx_giao_dich_dh_ma ON GIAO_DICH_THANH_TOAN(DH_MA);
CREATE UNIQUE INDEX uq_giao_dich_nhacc_yeucau ON GIAO_DICH_THANH_TOAN(GD_NHACC, GD_MA_YEUCAU);

CREATE TABLE QUAN_TRI_VIEN (
    QTV_MA SERIAL PRIMARY KEY,
    QTV_TENDN VARCHAR(255) NOT NULL UNIQUE,
    QTV_MATKHAU VARCHAR(255) NOT NULL,
    QTV_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE YEU_THICH (
    YT_MA SERIAL PRIMARY KEY,
    KH_MA INT NOT NULL REFERENCES KHACH_HANG(KH_MA) ON DELETE CASCADE,
    SP_MA INT NOT NULL REFERENCES SAN_PHAM(SP_MA) ON DELETE CASCADE,
    YT_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (KH_MA, SP_MA)
);

CREATE TABLE DANH_GIA (
    DG_MA SERIAL PRIMARY KEY,
    KH_MA INT NOT NULL REFERENCES KHACH_HANG(KH_MA) ON DELETE CASCADE,
    SP_MA INT NOT NULL REFERENCES SAN_PHAM(SP_MA) ON DELETE CASCADE,
    DG_SAO INT NOT NULL CHECK (DG_SAO BETWEEN 1 AND 5),
    DG_NOIDUNG TEXT,
    DG_TRANGTHAI VARCHAR(20) NOT NULL DEFAULT 'pending',
    DG_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (KH_MA, SP_MA)
);

CREATE TABLE TIN_NHAN (
    TN_MA SERIAL PRIMARY KEY,
    KH_MA INT NOT NULL REFERENCES KHACH_HANG(KH_MA) ON DELETE CASCADE,
    TN_NGUOIGUI VARCHAR(20) NOT NULL,
    TN_NOIDUNG TEXT NOT NULL,
    TN_DADOC BOOLEAN NOT NULL DEFAULT false,
    TN_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TRO_LY_AI (
    TL_MA SERIAL PRIMARY KEY,
    TL_PHIEN VARCHAR(64) NOT NULL,
    KH_MA INT REFERENCES KHACH_HANG(KH_MA) ON DELETE SET NULL,
    TL_VAITRO VARCHAR(20) NOT NULL,
    TL_NOIDUNG TEXT NOT NULL,
    TL_INTERACTION_ID VARCHAR(128),
    TL_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tro_ly_ai_phien ON TRO_LY_AI(TL_PHIEN, TL_NGAYTAO);

-- Cài đặt chung của site, dạng khóa/giá trị (phí giao hàng, thông báo trang chủ...).
CREATE TABLE CAI_DAT (
    CD_KHOA VARCHAR(50) PRIMARY KEY,
    CD_GIATRI TEXT,
    CD_NGAYCAPNHAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO CAI_DAT (CD_KHOA, CD_GIATRI) VALUES
    ('phi_giao_hang', '0'),
    ('thong_bao', '');