-- Migration: yêu thích, đánh giá sản phẩm, tồn kho, trò chuyện (chat)
-- Chạy trên DB đã có sẵn (không xóa dữ liệu hiện tại). Đã gộp vào ct271e_project.sql cho lần cài mới.

ALTER TABLE SAN_PHAM ADD COLUMN IF NOT EXISTS SP_TONKHO INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS YEU_THICH (
    YT_MA SERIAL PRIMARY KEY,
    KH_MA INT NOT NULL REFERENCES KHACH_HANG(KH_MA) ON DELETE CASCADE,
    SP_MA INT NOT NULL REFERENCES SAN_PHAM(SP_MA) ON DELETE CASCADE,
    YT_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (KH_MA, SP_MA)
);

CREATE TABLE IF NOT EXISTS DANH_GIA (
    DG_MA SERIAL PRIMARY KEY,
    KH_MA INT NOT NULL REFERENCES KHACH_HANG(KH_MA) ON DELETE CASCADE,
    SP_MA INT NOT NULL REFERENCES SAN_PHAM(SP_MA) ON DELETE CASCADE,
    DG_SAO INT NOT NULL CHECK (DG_SAO BETWEEN 1 AND 5),
    DG_NOIDUNG TEXT,
    DG_TRANGTHAI VARCHAR(20) NOT NULL DEFAULT 'pending', -- pending | approved | rejected
    DG_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (KH_MA, SP_MA)
);

CREATE TABLE IF NOT EXISTS TIN_NHAN (
    TN_MA SERIAL PRIMARY KEY,
    KH_MA INT NOT NULL REFERENCES KHACH_HANG(KH_MA) ON DELETE CASCADE,
    TN_NGUOIGUI VARCHAR(20) NOT NULL, -- 'customer' | 'admin'
    TN_NOIDUNG TEXT NOT NULL,
    TN_DADOC BOOLEAN NOT NULL DEFAULT false,
    TN_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
